"""create_tables

Revision ID: 2c2c5bd5234f
Revises: c1ab6592b88f
Create Date: 2026-02-26 22:19:39.291677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2c5bd5234f'
down_revision: Union[str, Sequence[str], None] = 'c1ab6592b88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('posting_number', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'posting_number', 'offer_id', name='uq_sales_seller_posting_offer')
    )
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_offer_id'), 'sales', ['offer_id'], unique=False)
    op.create_index(op.f('ix_sales_posting_number'), 'sales', ['posting_number'], unique=False)
    op.create_index(op.f('ix_sales_seller_id'), 'sales', ['seller_id'], unique=False)
    op.create_table('stocks_fbo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=False),
    sa.Column('cluster', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_fbo_cluster'), 'stocks_fbo', ['cluster'], unique=False)
    op.create_index(op.f('ix_stocks_fbo_offer_id'), 'stocks_fbo', ['offer_id'], unique=False)
    op.create_index(op.f('ix_stocks_fbo_seller_id'), 'stocks_fbo', ['seller_id'], unique=False)
    op.create_index('ix_stocks_fbo_seller_offer_asof', 'stocks_fbo', ['seller_id', 'offer_id', 'as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocks_fbo_seller_offer_asof', table_name='stocks_fbo')
    op.drop_index(op.f('ix_stocks_fbo_seller_id'), table_name='stocks_fbo')
    op.drop_index(op.f('ix_stocks_fbo_offer_id'), table_name='stocks_fbo')
    op.drop_index(op.f('ix_stocks_fbo_cluster'), table_name='stocks_fbo')
    op.drop_table('stocks_fbo')
    op.drop_index(op.f('ix_sales_seller_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_posting_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_offer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('sellers')
    # ### end Alembic commands ###
