"""add fk for ozon stock thresholds seller_id

Revision ID: 4d47f49a356f
Revises: a21cd7611c70
Create Date: 2026-03-18 18:07:42.818818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d47f49a356f'
down_revision: Union[str, Sequence[str], None] = 'a21cd7611c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ozon_stocks_product_id'), table_name='ozon_stocks')
    op.drop_index(op.f('ix_ozon_stocks_seller_id'), table_name='ozon_stocks')
    op.drop_index(op.f('ix_ozon_stocks_seller_wh'), table_name='ozon_stocks')
    op.drop_index(op.f('ix_ozon_stocks_stock_type'), table_name='ozon_stocks')
    op.drop_index(op.f('ix_ozon_stocks_synced_at'), table_name='ozon_stocks')
    op.drop_index(op.f('ix_ozon_stocks_warehouse_id'), table_name='ozon_stocks')
    op.drop_table('ozon_stocks')
    op.drop_index(op.f('ix_ozon_stock_thresholds_seller'), table_name='ozon_stock_thresholds')
    op.create_index(op.f('ix_ozon_stock_thresholds_seller_id'), 'ozon_stock_thresholds', ['seller_id'], unique=False)
    op.create_foreign_key(None, 'ozon_stock_thresholds', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ozon_stock_thresholds', type_='foreignkey')
    op.drop_index(op.f('ix_ozon_stock_thresholds_seller_id'), table_name='ozon_stock_thresholds')
    op.create_index(op.f('ix_ozon_stock_thresholds_seller'), 'ozon_stock_thresholds', ['seller_id'], unique=False)
    op.create_table('ozon_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stock_type', sa.VARCHAR(length=8), server_default=sa.text("'FBO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('free_to_sell', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reserved', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_ozon_stocks_seller_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('ozon_stocks_pkey')),
    sa.UniqueConstraint('seller_id', 'stock_type', 'warehouse_id', 'warehouse_name', 'product_id', name=op.f('uq_ozon_stocks_seller_type_whname_product'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ozon_stocks_warehouse_id'), 'ozon_stocks', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_ozon_stocks_synced_at'), 'ozon_stocks', ['synced_at'], unique=False)
    op.create_index(op.f('ix_ozon_stocks_stock_type'), 'ozon_stocks', ['stock_type'], unique=False)
    op.create_index(op.f('ix_ozon_stocks_seller_wh'), 'ozon_stocks', ['seller_id', 'warehouse_id'], unique=False)
    op.create_index(op.f('ix_ozon_stocks_seller_id'), 'ozon_stocks', ['seller_id'], unique=False)
    op.create_index(op.f('ix_ozon_stocks_product_id'), 'ozon_stocks', ['product_id'], unique=False)
    # ### end Alembic commands ###
