"""add ozon_connections_uuid

Revision ID: 6d67ce29672d
Revises: 8909f855092b
Create Date: 2026-03-01 18:13:35.102626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d67ce29672d'
down_revision: Union[str, Sequence[str], None] = '8909f855092b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('API_KEY', 'OAUTH', name='ozon_connection_type'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ozon_connections_seller_id'), 'ozon_connections', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ozon_connections_seller_id'), table_name='ozon_connections')
    op.drop_table('ozon_connections')
    # ### end Alembic commands ###
