"""sales_add_product_and_fees

Revision ID: 8909f855092b
Revises: 055419f60f74
Create Date: 2026-02-28 16:45:37.850055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8909f855092b'
down_revision: Union[str, Sequence[str], None] = '055419f60f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('commission', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('logistics', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.drop_constraint(op.f('sales_seller_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_seller_id_fkey'), 'sales', 'sellers', ['seller_id'], ['id'])
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_column('sales', 'logistics')
    op.drop_column('sales', 'commission')
    op.drop_column('sales', 'product_id')
    # ### end Alembic commands ###
