"""add_ozon_products

Revision ID: d292748f8afa
Revises: 6d67ce29672d
Create Date: 2026-03-01 21:23:49.924664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd292748f8afa'
down_revision: Union[str, Sequence[str], None] = '6d67ce29672d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('has_fbo_stocks', sa.Boolean(), nullable=False),
    sa.Column('has_fbs_stocks', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('is_discounted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'product_id', name='uq_ozon_products_seller_product')
    )
    op.create_index(op.f('ix_ozon_products_id'), 'ozon_products', ['id'], unique=False)
    op.create_index(op.f('ix_ozon_products_product_id'), 'ozon_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_ozon_products_seller_id'), 'ozon_products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ozon_products_seller_id'), table_name='ozon_products')
    op.drop_index(op.f('ix_ozon_products_product_id'), table_name='ozon_products')
    op.drop_index(op.f('ix_ozon_products_id'), table_name='ozon_products')
    op.drop_table('ozon_products')
    # ### end Alembic commands ###
