from datetime import date

from app.models.client import Client
from app.models.encounter import Encounter


def format_date_parts(value: date | None) -> tuple[str, str, str]:
    if value is None:
        return "", "", ""
    return value.strftime("%d"), value.strftime("%m"), value.strftime("%Y")


def build_document_context(client: Client, encounter: Encounter | None = None) -> dict[str, str]:
    birth_day, birth_month, birth_year = format_date_parts(client.birth_date)
    visit_day, visit_month, visit_year = format_date_parts(encounter.encounter_date if encounter else None)

    full_name = " ".join(part for part in [client.last_name, client.first_name, client.middle_name] if part).strip()
    first_middle = " ".join(part for part in [client.first_name, client.middle_name] if part).strip()
    visit_date = encounter.encounter_date.strftime("%d.%m.%Y") if encounter else ""
    total_amount = str(encounter.total_amount) if encounter else ""
    payment_type = encounter.payment_type if encounter else ""
    notes = encounter.comment if encounter and encounter.comment else ""
    sex_value = client.sex or ""
    sex_label = {"M": "муж", "F": "жен"}.get(sex_value.upper(), sex_value) if sex_value else ""

    context = {
        "ID": str(encounter.id if encounter else client.id),
        "ClientID": str(client.id),
        "ClientCalc": full_name,
        "LastNameCalc": client.last_name,
        "FirstNameCalc": client.first_name,
        "PatronymicCalc": client.middle_name or "",
        "FirstMiddleCalc": first_middle,
        "ReferenceNumber": str(encounter.id if encounter else client.id),
        "SeriesNumberCalc": str(encounter.id if encounter else client.id),
        "BirthDateCalc": client.birth_date.strftime("%d.%m.%Y") if client.birth_date else "",
        "BirthCalc": client.birth_date.strftime("%d.%m.%Y") if client.birth_date else "",
        "VisitDate_DATEFULL": visit_date,
        "BirthDateCalc_DAY": birth_day,
        "MonthBirthDateCalc": birth_month,
        "BirthDateCalc_YEAR": birth_year,
        "BirthDateCalc_DAY1": birth_day,
        "MonthBirthDateCalc1": birth_month,
        "BirthDateCalc_YEAR1": birth_year,
        "VisitDate": visit_date,
        "VisitDate_DAY": visit_day,
        "MonthCalc": visit_month,
        "VisitDate_YEAR": visit_year,
        "VisitDate_DAY1": visit_day,
        "MonthCalc1": visit_month,
        "VisitDate_YEAR1": visit_year,
        "SubjectCalc": client.address_text or "",
        "SubjectCalc1": client.address_text or "",
        "SubDistrCalc": client.address_text or "",
        "AddressEndCalc": client.address_text or "",
        "AddressCalc": client.address_text or "",
        "DistrictCalc": "",
        "DistrictCalc1": "",
        "CityCalc": "",
        "CityCalc1": "",
        "StreetCalc": "",
        "StreetCalc1": "",
        "HouseNumberCalc": "",
        "HouseNumberCalc1": "",
        "HouseBodyCalc": "",
        "HouseBodyCalc1": "",
        "ApartmentNumberCalc": "",
        "ApartmentNumberCalc1": "",
        "SexCalc": sex_label,
        "RegistrType": "постоянная",
        "UserName": "Администратор системы",
        "DateCalc": visit_date,
        "ServiceDateCalc": visit_date,
        "ServiceDateCalc1": visit_date,
        "StatusCalc": "Завершено" if encounter else "Создано",
        "VisitAmount": total_amount,
        "AllPayment": total_amount,
        "PaymentType": payment_type,
        "Notes": notes,
        "OrderService": "Базовая услуга",
        "qdfOrderServices": "Базовая услуга",
        "Post": "Не указано",
        "CompanyName": "Не указано",
        "qdfMain.AddressCalc": client.address_text or "",
        "qdfMain.PolisOMS": client.oms_policy or "",
        "qdfMain.SNILS": client.snils or "",
        "ContractNumber": f"Д-{encounter.id if encounter else client.id}",
        "MainDoctorCalc": "Главный врач",
        "Harmfulness": "Не указано",
        "Therapist": "Терапевт",
        "TherapistCalc": "Терапевт",
        "Ophthalmolog": "Офтальмолог",
        "OphthalmologCalc": "Офтальмолог",
        "Neurolog": "Невролог",
        "NeurologCalc": "Невролог",
        "Otolaryngolog": "Отоларинголог",
        "OtolaryngologCalc": "Отоларинголог",
        "InstrumentalExamination": "Без отклонений",
        "InstrumentalExaminationCalc": "Без отклонений",
        "LaboratoryStudy": "Без отклонений",
        "LaboratoryStudyCalc": "Без отклонений",
        "Conclusion": "Годен",
        "CategoryA": "",
        "CategoryB": "",
        "CategoryC": "",
        "CategoryD": "",
        "CategoryBE": "",
        "CategoryCE": "",
        "CategoryDE": "",
        "CategoryTm": "",
        "CategoryTb": "",
        "CategoryM": "",
        "Category1A": "",
        "Category1B": "",
        "Category1C": "",
        "Category1D": "",
        "Category1CE": "",
        "Category1DE": "",
        "CategoryA1": "",
        "CategoryB1": "",
        "CategoryC1": "",
        "CategoryD1": "",
        "CategoryBE1": "",
        "CategoryCE1": "",
        "CategoryDE1": "",
        "CategoryTm1": "",
        "CategoryTb1": "",
        "CategoryM1": "",
        "Category1A1": "",
        "Category1B1": "",
        "Category1C1": "",
        "Category1D1": "",
        "Category1CE1": "",
        "Category1DE1": "",
        "ACalc": "",
        "BCalc": "",
        "CCalc": "",
        "DCalc": "",
        "BECalc": "",
        "CECalc": "",
        "DECalc": "",
        "TmCalc": "",
        "TbCalc": "",
        "MCalc": "",
        "A1Calc": "",
        "B1Calc": "",
        "C1Calc": "",
        "D1Calc": "",
        "C1ECalc": "",
        "D1ECalc": "",
        "CategoryACalc": "",
        "CategoryBCalc": "",
        "CategoryCCalc": "",
        "DriveShipCalc": "",
        "ManualControlCalc": "",
        "AutomaticTransmissionCalc": "",
        "ParkingSystemCalc": "",
        "VisionTCCalc": "",
        "HearingTCCalc": "",
        "3040": "",
        "3201": "",
        "DrSh": "",
        "DrSh1": "",
        "TCA": "",
        "TCB": "",
        "TCC": "",
    }
    return context
